
# https://documentation.cpanel.net/display/CKB/Guide+to+Git+-+Deployment
#
# Website: https://webtradie.com
# GitHub: github.com/spencerjpotts
# Author: Spencer j Potts
# Date: 28/08/19
# Description: copy files into the appropriate directories to help the deployment of the website.
#
# 

deployment:
  tasks:
    # System Variable paths
    - export DEPLOYPATH=/home/webtradi/kenkeiso.webtradie.com/

    # HTML5 Static files
    - /bin/cp index.html $DEPLOYPATH

    # CSS Style Resources and Image asset resources
    - /bin/cp /styles/css $DEPLOYPATH
    - /bin/cp /js $DEPLOYPATH

    # 
    # - /bin/cp .htaccess $DEPLOYPATH